package com.example.tavanacity.core.contract.execution

import com.squareup.moshi.JsonClass

/**
 * Platform-Neutral Security Classification for execution plans.
 */
@JsonClass(generateAdapter = false)
enum class SecurityLevelDTO {
    SAFE,
    RESTRICTED,
    HIGH_RISK
}

/**
 * Platform-Neutral Step within an Execution Plan.
 */
@JsonClass(generateAdapter = true)
data class ExecutionStepDTO(
    val stepId: String,
    val actionType: String,
    val target: String,
    val payload: Map<String, String> = emptyMap(),
    val timeoutMs: Long = 5000L
)

/**
 * Platform-Neutral Plan generated by Orchestrator.
 */
@JsonClass(generateAdapter = true)
data class ExecutionPlanDTO(
    val planId: String,
    val taskId: String,
    val steps: List<ExecutionStepDTO>,
    val estimatedTokenCost: Int,
    val securityLevel: SecurityLevelDTO,
    val createdAt: Long
)

/**
 * Platform-Neutral Result of an individual step execution.
 */
@JsonClass(generateAdapter = true)
data class StepExecutionResultDTO(
    val stepId: String,
    val isSuccess: Boolean,
    val output: String,
    val logs: List<String> = emptyList(),
    val durationMs: Long = 0L,
    val error: String? = null
)

/**
 * Platform-Neutral Result of executing an entire Plan.
 */
@JsonClass(generateAdapter = true)
data class ExecutionResultDTO(
    val planId: String,
    val taskId: String,
    val isSuccess: Boolean,
    val stepResults: List<StepExecutionResultDTO>,
    val totalDurationMs: Long,
    val executionMetadata: Map<String, String> = emptyMap()
)
